-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tblcafeteria
(
    id serial NOT NULL,
    cafeteria_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    location character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tblcafeteria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblconcession
(
    id serial NOT NULL,
    concession_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    concessionaire_id integer NOT NULL,
    cafeteria_id integer NOT NULL,
    image bytea,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'open'::character varying,
    gcash_payment_available boolean DEFAULT false,
    oncounter_payment_available boolean DEFAULT true,
    gcash_number character varying(11) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    gcash_account_name character varying(50) COLLATE pg_catalog."default",
    receipt_timer time without time zone NOT NULL DEFAULT '00:15:00'::time without time zone,
    CONSTRAINT tblconcession_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblemailverification
(
    id serial NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    otp_code character varying(6) COLLATE pg_catalog."default",
    verification_token character varying(64) COLLATE pg_catalog."default",
    verification_type character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'email_verification'::character varying,
    expires_at timestamp without time zone NOT NULL,
    used boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    updated_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    CONSTRAINT tblemailverification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblfeedback
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    menu_item_id integer NOT NULL,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tblfeedback_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblitemvariation
(
    id serial NOT NULL,
    item_variation_group_id integer NOT NULL,
    variation_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    additional_price numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    image bytea,
    max_amount integer DEFAULT 1,
    available boolean,
    CONSTRAINT tblitemvariation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblitemvariationgroup
(
    id serial NOT NULL,
    variation_group_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    menu_item_id integer NOT NULL,
    multiple_selection boolean DEFAULT false,
    required_selection boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    max_selection integer DEFAULT 1,
    min_selection integer DEFAULT 0,
    min_selection_required boolean DEFAULT false,
    max_selection_required boolean DEFAULT false,
    CONSTRAINT tblitemvariationgroup_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblmenuitem
(
    id serial NOT NULL,
    item_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    concession_id integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    image bytea,
    category character varying(100) COLLATE pg_catalog."default",
    available boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    take_out_additional_fee numeric(10, 2) DEFAULT 0,
    CONSTRAINT tblmenuitem_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblnotification
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    notification_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    order_id integer,
    CONSTRAINT tblnotification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblorder
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    concession_id integer NOT NULL,
    schedule_time timestamp without time zone,
    total_price numeric(10, 2),
    order_status character varying(30) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    payment_method character varying(20) COLLATE pg_catalog."default" DEFAULT 'on-counter'::character varying,
    in_cart boolean DEFAULT false,
    gcash_screenshot bytea,
    decline_reason text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    updated_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    payer_customer_id integer,
    updated_total_price numeric(10, 2),
    price_change_reason text COLLATE pg_catalog."default",
    payment_verified boolean NOT NULL DEFAULT false,
    payment_rejected_reason text COLLATE pg_catalog."default",
    accepted_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    payment_receipt_expires_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    reopening_requested boolean DEFAULT false,
    reopened_at timestamp without time zone,
    original_decline_reason text COLLATE pg_catalog."default",
    reopening_count integer DEFAULT 0,
    CONSTRAINT tblorder_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.tblorder.reopening_requested
    IS 'Indicates if customer has requested to reopen this order';

COMMENT ON COLUMN public.tblorder.reopened_at
    IS 'Timestamp when the order was reopened by concessionaire';

COMMENT ON COLUMN public.tblorder.original_decline_reason
    IS 'Stores the original decline reason before reopening';

COMMENT ON COLUMN public.tblorder.reopening_count
    IS 'Number of times this order has been reopened';

CREATE TABLE IF NOT EXISTS public.tblorderdetail
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity integer NOT NULL,
    item_price numeric(10, 2) NOT NULL,
    total_price numeric(10, 2) NOT NULL,
    note text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    updated_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    dining_option character varying(10) COLLATE pg_catalog."default" DEFAULT 'dine-in'::character varying,
    CONSTRAINT tblorderdetail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblorderitemvariation
(
    id serial NOT NULL,
    order_detail_id integer NOT NULL,
    variation_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    updated_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    quantity integer,
    CONSTRAINT tblorderitemvariation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tblorderreopeningrequest
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    customer_id integer NOT NULL,
    concessionaire_id integer NOT NULL,
    request_message text COLLATE pg_catalog."default" NOT NULL,
    request_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'custom'::character varying,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    response_message text COLLATE pg_catalog."default",
    response_type character varying(50) COLLATE pg_catalog."default",
    requested_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    responded_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    updated_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
    CONSTRAINT tblorderreopeningrequest_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.tblorderreopeningrequest
    IS 'Stores requests from customers to reopen declined orders';

COMMENT ON COLUMN public.tblorderreopeningrequest.request_type
    IS 'Type of reopening request: custom, missed_deadline, technical_issue, payment_delay, forgot_upload, network_issue, busy_schedule, etc.';

COMMENT ON COLUMN public.tblorderreopeningrequest.status
    IS 'Status of the request: pending, approved, rejected';

COMMENT ON COLUMN public.tblorderreopeningrequest.response_type
    IS 'Type of response: approved, cannot_fulfill, out_of_stock, time_passed, business_hours, capacity_full, repeated_violation, custom, etc.';

CREATE TABLE IF NOT EXISTS public.tbluser
(
    id serial NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'customer'::character varying,
    profile_image bytea,
    email_verified boolean DEFAULT false,
    profile_created boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    contact_number character varying(11) COLLATE pg_catalog."default",
    messenger_link character varying(255) COLLATE pg_catalog."default",
    last_password_reset timestamp without time zone,
    password_reset_count integer DEFAULT 0,
    account_locked boolean DEFAULT false,
    locked_until timestamp without time zone,
    login_attempts integer DEFAULT 0,
    last_login timestamp without time zone,
    CONSTRAINT tbluser_pkey PRIMARY KEY (id),
    CONSTRAINT tbluser_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.tblconcession
    ADD CONSTRAINT fk_cafeteria FOREIGN KEY (cafeteria_id)
    REFERENCES public.tblcafeteria (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblconcession
    ADD CONSTRAINT fk_concessionaire FOREIGN KEY (concessionaire_id)
    REFERENCES public.tbluser (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblfeedback
    ADD CONSTRAINT fk_feedback_customer FOREIGN KEY (customer_id)
    REFERENCES public.tbluser (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblfeedback
    ADD CONSTRAINT fk_feedback_menuitem FOREIGN KEY (menu_item_id)
    REFERENCES public.tblmenuitem (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblitemvariation
    ADD CONSTRAINT fk_item_variation_group FOREIGN KEY (item_variation_group_id)
    REFERENCES public.tblitemvariationgroup (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblitemvariationgroup
    ADD CONSTRAINT fk_menuitem_variation_group FOREIGN KEY (menu_item_id)
    REFERENCES public.tblmenuitem (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblmenuitem
    ADD CONSTRAINT fk_concession FOREIGN KEY (concession_id)
    REFERENCES public.tblconcession (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblnotification
    ADD CONSTRAINT fk_order_notification FOREIGN KEY (order_id)
    REFERENCES public.tblorder (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblnotification
    ADD CONSTRAINT fk_user_notification FOREIGN KEY (user_id)
    REFERENCES public.tbluser (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblorder
    ADD CONSTRAINT fk_customer FOREIGN KEY (customer_id)
    REFERENCES public.tbluser (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblorder
    ADD CONSTRAINT fk_order_concession FOREIGN KEY (concession_id)
    REFERENCES public.tblconcession (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblorder
    ADD CONSTRAINT fk_order_payer FOREIGN KEY (payer_customer_id)
    REFERENCES public.tbluser (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tblorderdetail
    ADD CONSTRAINT fk_order FOREIGN KEY (order_id)
    REFERENCES public.tblorder (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblorderdetail
    ADD CONSTRAINT fk_order_item FOREIGN KEY (item_id)
    REFERENCES public.tblmenuitem (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblorderitemvariation
    ADD CONSTRAINT fk_order_variation FOREIGN KEY (variation_id)
    REFERENCES public.tblitemvariation (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblorderitemvariation
    ADD CONSTRAINT fk_orderdetail_variation FOREIGN KEY (order_detail_id)
    REFERENCES public.tblorderdetail (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tblorderreopeningrequest
    ADD CONSTRAINT tblorderreopeningrequest_concessionaire_id_fkey FOREIGN KEY (concessionaire_id)
    REFERENCES public.tbluser (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reopening_request_concessionaire_id
    ON public.tblorderreopeningrequest(concessionaire_id);


ALTER TABLE IF EXISTS public.tblorderreopeningrequest
    ADD CONSTRAINT tblorderreopeningrequest_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.tbluser (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reopening_request_customer_id
    ON public.tblorderreopeningrequest(customer_id);


ALTER TABLE IF EXISTS public.tblorderreopeningrequest
    ADD CONSTRAINT tblorderreopeningrequest_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.tblorder (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reopening_request_order_id
    ON public.tblorderreopeningrequest(order_id);

END;